spring:
  profiles:
    active: develop
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  freemarker:
    suffix: .ftlh

server:
  servlet:
    session:
      cookie:
        http-only: true

app:
  name: tire.ho
---

spring:
  profiles: develop
  datasource:
    url:
    username: tireho
    password: tireho
  jpa:
    hibernate.ddl-auto: update
    show-sql: true                        #  SQL 로그
    properties.hibernate.format_sql: true #  SQL 문 보기 좋게
