spring:
  profiles:
    active: develop
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  freemarker:
    suffix: .ftlh
  datasource:
    url: jdbc:mysql://localhost:3306/tireho?useSSL=false
    username: tireho
    password: tireho
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

server:
  servlet:
    session:
      cookie:
        http-only: true





app:
  name: base
  creator: tire.ho
